### ISSUE TITLE
In what format should start time and termination time be provided?

### ISSUE THREAD

**Issue by damian101** [mboljen/cropdetect#1]
Tried a few things, can't get it to work.

**Comment by mboljen** [comment]
Please try again. Integer values will be interpreted as seconds. You can also use floating point values for fractions of seconds. Addtionally, I added several regular expressions and an internal function to convert timestamps using the format `HH:MM:SS.sss` to plain seconds.

**Comment by damian101** [comment]
> Please pull my latest commit and try again. Integer values will be interpreted as seconds. You can also use floating point values for fractions of seconds. Addtionally, I added several regular expressions and an internal function to convert timestamps using the format `HH:MM:SS.sss` to plain seconds.

works great :)
